version: "3.7"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./docker/postgres.init.sh:/docker-entrypoint-initdb.d/postgres.init.sh
    networks:
      - flask-app

networks:
  flask-app:
    name: flask-app
