openapi: 3.0.2

info:
  description: Server API document
  title: Server API
  version: 1.0.0

servers:
- url: http://localhost:{port}/
  description: The development API server
  variables:
    port:
      enum:
      - '3000'
      - '8888'
      default: '3000'

paths: {}
